### ISSUE TITLE
App not working if redis unavailable

### ISSUE THREAD

**Issue by knutov** [yanick/Dancer-Plugin-Cache-CHI#9]
Caching is not mandatory service in most cases, I think.
I should use Redis as backend for CHI in case I need to be able clear cache for all app processes.
Redis (as caching at all) is not critical service and can be not running.

As for now I got exception in this case and app totally not working when I expecting only not working caching (undef on cache->get and doing nothing on cache->set).

Is it possible to change this behavior?

**Comment by knutov** [comment]
I do not like the idea to have large chain of helpers of helpers. I understand I can fork or write my own implementation for caching, but this is not optimal way, I think.

Is there an easy way to have fallback driver (Null) to use when connection with main driver (Redis) was not successful?

**Comment by yanick** [comment]
On 2015-01-01 01:52 AM, Nick S. Knutov wrote:
> Is there an easy way to have fallback driver (Null) to use when
> connection with main driver (Redis) was not successful?

The easiest would be to set the CHI driver (Null or Redis) at
configuration time. If you want to react if Redis goes dead at some
point, you can do something like

   sub do_the_caching_stuff {
       eval {
         alarm 2;
         [try with redis]
         alarm 0;
       };
       if( $@ ) {
	 [ Redis failed us, set driver to Null ]
       }
   }
